export default [
  {
    title: "Home",
    icon: "home",
    iconType: "feather",
    type: "LINK",
    to: "/dashboards",
  },
  {
    header: "Apps",
  },
  {
    title: "សំណើរ",
    icon: "mdi-check-all",
    iconType: "feather",
    type: "LINK",
    to: "/case-board",
  }, 
  {
    title: "លេខទូរស័ព្ទ",
    icon: "mdi-contacts",
    type: "LINK",
    iconType: "feather",
    to: "/contacts",
  },
  {
    title: "ផលិតិផល",
    icon: "mdi-cube-outline",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/items",
  }, 
  { header: "ប្រព័ន្ធ" },
  {
    title: "អ្នកប្រើប្រាស់",
    icon: "mdi-account-outline",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/users",
  },
  {
    title: "សាខា",
    icon: "mdi-store",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/branches",
  },
  {
    title: "ឈ្មោះព៍ណ",
    icon: "mdi-palette-outline",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/colors",
  },
  {
    title: "ឈ្មោះគំរូ",
    icon: "mdi-format-list-bulleted-type",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/models",
  },
  {
    title: "ស្ថានភាពយានយន្ដ",
    icon: "mdi-checkbox-marked-circle-outline",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/conditions",
  },
  {
    title: "ប្រភេទទំនិញ",
    icon: "mdi-file-tree",
    type: "DOCUMENT_LIST",
    iconType: "feather",
    to: "/categories",
  }
];
